/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2017-12-22 08:10:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class kids_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".row.flex{display:inline-flex;  width:100%;}\r\n");
      out.write("img{width:50%;height=auto;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\" >\r\n");
      out.write("  <div class=\"col-xs-3\">\r\n");
      out.write("    <div class=\"thumbnail\">\r\n");
      out.write("      <a href=\"./resources/img1.jpg\">\r\n");
      out.write("        <img src=\"./resources/img1.jpg\" >\r\n");
      out.write("        <div class=\"caption\">\r\n");
      out.write("          <p></p><p>Marvel Ultimate Spiderman 20T<br>Rs.5,750/-</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-xs-3\">\r\n");
      out.write("    <div class=\"thumbnail\" >\r\n");
      out.write("      <a href=\"./resources/img2.jpg\">\r\n");
      out.write("        <img src=\"./resources/img2.jpg\" >\r\n");
      out.write("        <div class=\"caption\">\r\n");
      out.write("          <p>Captain America 20T<br>Rs.6,625/-</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-xs-3\">\r\n");
      out.write("    <div class=\"thumbnail\">\r\n");
      out.write("      <a href=\"./resources/img3.jpg\">\r\n");
      out.write("        <img src=\"./resources/img3.jpg\">\r\n");
      out.write("        <div class=\"caption\">\r\n");
      out.write("          <p>Avengers - Age of Ultrons 20T<br>Rs.6,700/-</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div> \r\n");
      out.write("  <div class=\"col-xs-3\">\r\n");
      out.write("    <div class=\"thumbnail\">\r\n");
      out.write("      <a href=\"./resources/img4.jpg\">\r\n");
      out.write("        <img src=\"./resources/img4.jpg\"  >\r\n");
      out.write("        <div class=\"caption\">\r\n");
      out.write("          <p>Avengers Ironman 20T<br>Rs.6,775/-</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\" >\r\n");
      out.write("  <div class=\"col-xs-3\">\r\n");
      out.write("    <div class=\"thumbnail\">\r\n");
      out.write("      <a href=\"./resources/img5.jpg\">\r\n");
      out.write("        <img src=\"./resources/img5.jpg\" >\r\n");
      out.write("        <div class=\"caption\">\r\n");
      out.write("          <p>Princess 12T(Pink)<br>Rs.4725/- </p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-xs-3\">\r\n");
      out.write("    <div class=\"thumbnail\" >\r\n");
      out.write("      <a href=\"./resources/img6.jpg\">\r\n");
      out.write("        <img src=\"./resources/img6.jpg\" >\r\n");
      out.write("        <div class=\"caption\">\r\n");
      out.write("          <p>Mickey & Friends 12T<br> Rs.4,300/-</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-xs-3\">\r\n");
      out.write("    <div class=\"thumbnail\">\r\n");
      out.write("      <a href=\"./resources/img7.jpg\">\r\n");
      out.write("        <img src=\"./resources/img7.jpg\">\r\n");
      out.write("        <div class=\"caption\">\r\n");
      out.write("          <p>Princess 16T(Pink)<br>Rs.5225/-</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div> \r\n");
      out.write("  <div class=\"col-xs-3\">\r\n");
      out.write("    <div class=\"thumbnail\">\r\n");
      out.write("      <a href=\"./resources/img8.jpg\">\r\n");
      out.write("        <img src=\"./resources/img8.jpg\"  >\r\n");
      out.write("        <div class=\"caption\">\r\n");
      out.write("          <p>Mickey & Friends 12T<br> Rs.4,750/-</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\t<div class=\"col-xs-3\">\r\n");
      out.write("    <div class=\"thumbnail\">\r\n");
      out.write("      <a href=\"./resources/baby4.jpg\">\r\n");
      out.write("        <img src=\"./resources/baby4.jpg\">\r\n");
      out.write("        <div class=\"caption\">\r\n");
      out.write("          <p>Mee Mee Baby Cycle Tricycle  (Red)</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t<div class=\"col-xs-3\">\r\n");
      out.write("    <div class=\"thumbnail\">\r\n");
      out.write("      <a href=\"./resources/baby5.jpg\">\r\n");
      out.write("        <img src=\"./resources/baby5.jpg\">\r\n");
      out.write("        <div class=\"caption\">\r\n");
      out.write("          <p>Mee Mee Baby Cycle Tricycle  (Red)</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"col-xs-3\">\r\n");
      out.write("    <div class=\"thumbnail\">\r\n");
      out.write("      <a href=\"./resources/kid2.jpg\">\r\n");
      out.write("        <img src=\"./resources/kid2.jpg\">\r\n");
      out.write("        <div class=\"caption\">\r\n");
      out.write("          <p>Hero Kids Bicycle Blaze 16 T</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"col-xs-3\">\r\n");
      out.write("    <div class=\"thumbnail\">\r\n");
      out.write("      <a href=\"./resources/cycle3.jpg\">\r\n");
      out.write("        <img src=\"./resources/cycle3.jpg\">\r\n");
      out.write("        <div class=\"caption\">\r\n");
      out.write("          <p>Mee Mee Baby Cycle Tricycle  (Red)</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
